### ISSUE TITLE
Not able to upload full story to SqlLite

### ISSUE THREAD

**Issue by stagnoman** [leshiy960/pars_investing_news#1]
Hi there, interesting project. I have only one question: how can I upload the full story into SqlLite database?
it is currently empty: from python code I found full = ''
Do you know the right python script to upload full story? 

thank you so much for your help
Regards
LUCA

**Comment by leshiy960** [comment]
Hi lucastagnitta, now this feature is in the dev branch. How will the time be I will include it in the main branch.

**Comment by leshiy960** [comment]
version 1.1 is ready, full article download function should work :)

but some links may not be parsed, so i will look for a solution

**Comment by stagnoman** [comment]
great thks a lot

    Il venerdì 4 dicembre 2020, 16:20:55 CET, leshiy960 <notifications@github.com> ha scritto:  
 
 


Closed #1.
